---
- name: ALB and Target Group Management
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - group_vars/main.yml

  tasks:
    - name: Deploy ALB Resources
      include_role:
        name: loadbalancer
      when: action == "deploy"

    - name: Terminate ALB Resources
      include_role:
        name: loadbalancer
        tasks_from: terminate
      when: action == "terminate"
