pipeline {
  agent any

  tools {
    jdk 'JDK21'
    maven 'M3'
  }
  environment {
    // 환경변수 지정
    REGION = 'ap-northeast-2'
    AWS_ACCOUNT_ID = 'YOUR_AWS_ACCOUNT_ID'
    PREFIX = 'user02'

    DOCKER_IMAGE_NAME = "spring-petclinic"
    DOCKERHUB_NAMESPACE = 'tmddbs1977'
    
    S3_BUCKET = "${PREFIX}-codedeploy-bucket"
    CODEDEPLOY_APP = "${PREFIX}-code-deploy"
    CODEDEPLOY_GROUP = "${PREFIX}-code-deploy-group"
    ASG_NAME = "${PREFIX}-app-asg"

    // Credentials
    DOCKERHUB_CRED = credentials('dockerCredentials')
  }

  stages {
    stage('Git Clone') {
      steps {
        git url: 'https://github.com/tmddbs1977/spring-petclinic.git', 
        branch: 'main'
      }
    }
    stage('Maven Build') {
      steps {
        echo 'Maven Build'
        sh 'mvn clean package'
      }
    }
            
    stage('Docker Build && Push') {
      steps {
        sh '''          
          docker build -t ${DOCKER_IMAGE_NAME}:${BUILD_NUMBER} .
          docker tag ${DOCKER_IMAGE_NAME}:${BUILD_NUMBER} ${DOCKERHUB_NAMESPACE}/${DOCKER_IMAGE_NAME}:${BUILD_NUMBER}
          docker tag ${DOCKER_IMAGE_NAME}:${BUILD_NUMBER} ${DOCKERHUB_NAMESPACE}/${DOCKER_IMAGE_NAME}:latest
          echo ${DOCKERHUB_CRED_PSW} | docker login -u ${DOCKERHUB_CRED_USR} --password-stdin
          docker push ${DOCKERHUB_NAMESPACE}/${DOCKER_IMAGE_NAME}:${BUILD_NUMBER}
          docker push ${DOCKERHUB_NAMESPACE}/${DOCKER_IMAGE_NAME}:latest
        '''
      }
      post {
        always {
          sh '''
          docker rmi -f ${DOCKER_IMAGE_NAME}:${BUILD_NUMBER} || true
          docker rmi -f ${DOCKERHUB_NAMESPACE}/${DOCKER_IMAGE_NAME}:${BUILD_NUMBER} || true
          docker rmi -f ${DOCKERHUB_NAMESPACE}/${DOCKER_IMAGE_NAME}:latest || true
          '''
        }
      }
    }
    stage('Upload s3') {
      steps {
        echo "Upload to S3"
          dir("${env.WORKSPACE}") {
              sh 'zip -r scripts.zip ./scripts appspec.yml'
              withAWS(region:"${REGION}"){
                  s3Upload(file:"scripts.zip", bucket:"${S3_BUCKET}")
              }
              sh 'rm -rf ./scripts.zip'
          }
      }
    }

    stage('Codedeploy workload') {
      steps {
          echo "Update/Create code-deploy group"
          sh """
          # 기존 배포 그룹이 있으면 업데이트, 없으면 생성
          aws deploy create-deployment-group \
          --application-name ${CODEDEPLOY_APP} \
          --auto-scaling-groups ${ASG_NAME} \
          --deployment-group-name ${CODEDEPLOY_GROUP} \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --service-role-arn arn:aws:iam::${AWS_ACCOUNT_ID}:role/${PREFIX}-codedeploy-service-role \
          || aws deploy update-deployment-group \
          --application-name ${CODEDEPLOY_APP} \
          --auto-scaling-groups ${ASG_NAME} \
          --current-deployment-group-name ${CODEDEPLOY_GROUP} \
          --service-role-arn arn:aws:iam::${AWS_ACCOUNT_ID}:role/${PREFIX}-codedeploy-service-role
          """
          
          echo "Executing deployment"
          sh """
          aws deploy create-deployment \
          --application-name ${CODEDEPLOY_APP} \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --deployment-group-name ${CODEDEPLOY_GROUP} \
          --s3-location bucket=${S3_BUCKET},bundleType=zip,key=scripts.zip
          """
      }
    }    
  }
}
